spring.application.name=ticketingsystem

# ===============================
# MySQL Database
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/ticketing_system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Groq (Values overridden locally)
# ===============================

groq.api.key=
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile

spring.config.import=optional:application-local.properties